import { promises as fs } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';
import { discoverRouteFiles } from './compiler.js';
import { fileToRoutePath } from './router.js';
import type { RouteParams } from './types.js';

export interface GeneratedDxResult {
  outDir: string;
  routesFile: string;
  configFile: string;
  routeCount: number;
}

export async function generateDxTypes(rootDir: string, outDir = '.ryvax'): Promise<GeneratedDxResult> {
  const root = resolve(rootDir);
  const destination = resolve(root, outDir);
  const files = await discoverRouteFiles(root);
  const routes = files.filter((file) => {
    const appRoot = resolve(root, 'app');
    if (file.startsWith(appRoot + sep)) {
      const relativeFile = relative(appRoot, file).split(sep).join('/');
      return /(^|\/)(page|route)\.[^.]+$/.test(relativeFile);
    }
    return file.startsWith(resolve(root, 'pages') + sep);
  }).map((file) => {
    const routeRoot = file.startsWith(resolve(root, 'app') + sep) ? resolve(root, 'app') : resolve(root, 'pages');
    const info = fileToRoutePath(file, routeRoot);
    const relativeFile = relative(routeRoot, file).split(sep).join('/');
    return { file: relativeFile, ...info };
  });
  const unique = [...new Map(routes.map((route) => [route.pathname + ':' + route.file, route])).values()].sort((a, b) => a.pathname.localeCompare(b.pathname) || a.file.localeCompare(b.file));
  await fs.rm(destination, { recursive: true, force: true });
  await fs.mkdir(destination, { recursive: true });
  const routesFile = join(destination, 'routes.d.ts');
  const configFile = join(destination, 'config.d.ts');
  await fs.writeFile(routesFile, renderRoutes(unique));
  await fs.writeFile(configFile, renderConfig());
  return { outDir: destination, routesFile, configFile, routeCount: unique.length };
}

function renderRoutes(routes: Array<{ pathname: string; segments: string[]; dynamic: boolean; catchAll: boolean }>): string {
  const paths = [...new Set(routes.map((route) => route.pathname))].sort();
  const params = routes.filter((route) => route.dynamic).map((route) => {
    const fields = route.segments.filter((segment) => segment.startsWith(':') || segment.startsWith('*')).map((segment) => {
      const optional = segment.endsWith('?');
      const name = segment.replace(/^\*/, '').replace(/^:/, '').replace(/\?$/, '');
      const property = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
      return `  ${property}: ${segment.startsWith('*') ? 'string[]' : 'string'}${optional ? ' | undefined' : ''};`;
    });
    const typeName = route.pathname === '/' ? 'RootRouteParams' : `${route.pathname.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => String(c).toUpperCase()).replace(/^./, (c) => c.toUpperCase())}RouteParams`;
    return `export interface ${typeName} {\n${fields.join('\n')}\n}`;
  });
  return `// Generated by Ryvax. Do not edit.\nexport type RyvaxRoute = ${paths.length ? paths.map((path) => JSON.stringify(path)).join(' | ') : 'never'};\nexport type RyvaxRouteParams = Record<string, string | string[] | undefined>;\nexport function route(path: RyvaxRoute): RyvaxRoute;\n${params.join('\n\n')}\n`;
}

function renderConfig(): string {
  return `// Generated by Ryvax. Do not edit.\nexport type RyvaxConfigFile = 'framework.config.ts' | 'framework.config.mts' | 'framework.config.js' | 'framework.config.mjs';\nexport declare const ryvaxConfigFile: RyvaxConfigFile;\n`;
}

export type GeneratedRouteParams = RouteParams;
